### Liftover

In [1]:
import gwaslab as gl
import pandas as pd

In [2]:
gl.show_version()

2026/03/12 02:37:14 GWASLab v4.0.4 https://cloufield.github.io/gwaslab/
2026/03/12 02:37:14 (C) 2022-2026, Yunye He, Kamatani Lab, GPL-3.0 license, gwaslab@gmail.com
2026/03/12 02:37:14 Python version: 3.12.3 (main, Mar  3 2026, 12:15:18) [GCC 13.3.0]

In [ ]:
# # Load the dataset using the confirmed headers
# mysumstats = gl.Sumstats(
#     "/mnt/hdd_1/ofgeha/galaxy-gwas-tools/Data/21001_raw.gwas.imputed_v3.both_sexes.tsv.bgz",
#     snpid="variant",           
#     ea="minor_allele",         
#     neaf="minor_AF",           
#     beta="beta",
#     se="se",
#     p="pval",
#     verbose=True,
#     readargs={
#         "compression": "gzip",
#         "sep": "\t"
#     }
# )

In [3]:
mysumstats = gl.Sumstats(
    "/mnt/hdd_1/ofgeha/galaxy-gwas-tools/Data/21001_raw.gwas.imputed_v3.both_sexes.tsv.bgz",
    snpid="variant",
    ea="minor_allele",
    eaf="minor_AF",
    beta="beta",
    se="se",
    p="pval",
    n="n_complete_samples",
    other=["low_confidence_variant", "AC", "ytx"],
    readargs={
        "compression": "gzip",
        "sep": "\t"
    },
    verbose=True
)

2026/03/12 02:37:20 GWASLab v4.0.4 https://cloufield.github.io/gwaslab/
2026/03/12 02:37:20 (C) 2022-2026, Yunye He, Kamatani Lab, GPL-3.0 license, gwaslab@gmail.com
2026/03/12 02:37:20 Python version: 3.12.3 (main, Mar  3 2026, 12:15:18) [GCC 13.3.0]
2026/03/12 02:37:20 Start to initialize gl.Sumstats from file :/mnt/hdd_1/ofgeha/galaxy-gwas-tools/Data/21001_raw.gwas.imputed_v3.both_sexes.tsv.bgz
2026/03/12 02:37:45  -Reading columns          : AC,minor_allele,n_complete_samples,variant,ytx,se,beta,low_confidence_variant,pval,minor_AF
2026/03/12 02:37:45  -Renaming columns to      : AC,EA,N,SNPID,ytx,SE,BETA,low_confidence_variant,P,EAF
2026/03/12 02:37:45  -Current Dataframe shape : 13791467  x  10
2026/03/12 02:37:45  -Initiating a status column: STATUS ...
2026/03/12 02:37:45 #WARNING! Version of genomic coordinates is unknown for homo sapiens (build: 99)...
2026/03/12 02:37:46 Start to reorder the columns ...(v4.0.4)
2026/03/12 02:37:46  -Reordering columns to    : SNPID,EA,STATUS,EAF,BETA,SE,P,N,low_confidence_variant,AC,ytx
2026/03/12 02:37:48 Finished reordering the columns.
2026/03/12 02:37:48  -Column  : SNPID  EA       STATUS EAF     BETA    SE      P       N     low_confidence_variant AC      ytx
2026/03/12 02:37:48  -DType   : object category int64  float64 float64 float64 float64 int64 bool                   float64 float64
2026/03/12 02:37:48  -Verified: T      T        T      T       T       T       T       T     NA                     NA      NA
2026/03/12 02:37:49  -Current Dataframe memory usage: 1014.01 MB
2026/03/12 02:37:49 Finished loading data successfully!

In [4]:
mysumstats.data

,SNPID,EA,STATUS,EAF,BETA,SE,P,N,low_confidence_variant,AC,ytx
0,1:15791:C:T,T,9999999,5.446880e-09,894.616000,1204.870000,0.457786,359983,True,0.003922,1.238950e-01
1,1:69487:G:A,A,9999999,5.768250e-06,-2.715450,2.360060,0.249902,359983,True,4.152940,1.035150e+02
2,1:69569:T:C,C,9999999,1.878960e-04,-0.484284,0.423462,0.252778,359983,True,135.278000,3.644560e+03
3,1:139853:C:T,T,9999999,5.681100e-06,-2.703560,2.360130,0.251997,359983,True,4.090200,1.018400e+02
4,1:692794:CA:C,C,9999999,1.105900e-01,-0.016436,0.019585,0.401342,359983,False,79621.100000,2.179000e+06
...,...,...,...,...,...,...,...,...,...,...,...
13791462,X:154929412:C:T,T,9999999,2.454730e-01,-0.016260,0.010723,0.129427,359983,False,176732.000000,4.837480e+06
13791463,X:154929637:CT:C,C,9999999,2.297260e-01,-0.027098,0.011190,0.015456,359983,False,165395.000000,4.525550e+06
13791464,X:154929952:CAA:C,C,9999999,2.394300e-01,-0.020494,0.011278,0.069202,359983,False,172381.000000,4.717910e+06
13791465,X:154930230:A:G,G,9999999,2.458870e-01,-0.016347,0.010721,0.127334,359983,False,177030.000000,4.845680e+06
13791466,X:154930487:T:A,A,9999999,1.955900e-02,0.007107,0.036783,0.846790,359983,False,14081.800000,3.857390e+05

In [5]:
# 1. Manually split the SNPID string into separate columns
# This splits "1:69487:G:A" into 4 columns
split_cols = mysumstats.data['SNPID'].str.split(':', expand=True)

In [6]:
# 2. Assign the split values to the expected column names
mysumstats.data['CHR'] = split_cols[0]
mysumstats.data['POS'] = split_cols[1].astype(int)  # Liftover needs POS as an integer
mysumstats.data['NEA'] = split_cols[2]

In [7]:
# 3. Verify the columns are actually there now
print("Actual columns in dataframe:", mysumstats.data.columns)
print(mysumstats.data[['SNPID', 'CHR', 'POS']].head())

Actual columns in dataframe: Index(['SNPID', 'EA', 'STATUS', 'EAF', 'BETA', 'SE', 'P', 'N',
       'low_confidence_variant', 'AC', 'ytx', 'CHR', 'POS', 'NEA'],
      dtype='object')
           SNPID CHR     POS
0    1:15791:C:T   1   15791
1    1:69487:G:A   1   69487
2    1:69569:T:C   1   69569
3   1:139853:C:T   1  139853
4  1:692794:CA:C   1  692794

### Liftover

In [8]:
mysumstats.basic_check()

2026/03/12 02:38:28 Start to check SNPID/rsID ...(v4.0.4)
2026/03/12 02:38:28  -Current Dataframe shape : 13791467 x 14 ; Memory usage: 1329.68 MB
2026/03/12 02:38:28  -Checking SNPID data type...
2026/03/12 02:38:28  -Converted datatype for SNPID: object -> string
2026/03/12 02:38:28  -Checking if SNPID contains NA strings :na,NA,Na,Nan,NaN,<NA>,null,NULL,#N/A,#VALUE!,N/A,n/a,missing,...
2026/03/12 02:38:29  -Checking if SNPID is CHR:POS:NEA:EA...(separator: - ,: , _)
2026/03/12 02:38:34 Finished checking SNPID/rsID.
2026/03/12 02:38:34 Start to fix chromosome notation (CHR) ...(v4.0.4)
2026/03/12 02:38:34  -Checking CHR data type...
2026/03/12 02:38:34  -Variants with standardized chromosome notation: 13364303
2026/03/12 02:38:35  -Variants with fixable chromosome notations: 427164
2026/03/12 02:38:35  -No unrecognized chromosome notations...
2026/03/12 02:38:35  -Identifying non-autosomal chromosomes : X, Y, and MT ...
2026/03/12 02:38:35  -Identified 427164 variants on sex chromosomes...
2026/03/12 02:38:35  -Standardizing first sex chromosome chromosome notations: X to 23...
2026/03/12 02:38:36 Finished fixing chromosome notation (CHR).
2026/03/12 02:38:36 Start to fix basepair positions (POS) ...(v4.0.4)
2026/03/12 02:38:36  -Trying to convert datatype for POS: int64 -> Int64...
2026/03/12 02:38:37  -Position bound:(0 , 250,000,000)
2026/03/12 02:38:37  -No outlier variants were removed.
2026/03/12 02:38:40 Finished fixing basepair positions (POS).
2026/03/12 02:38:40 Start to fix alleles (EA and NEA) ...(v4.0.4)
2026/03/12 02:38:40  -Converted all bases to string datatype and UPPERCASE
2026/03/12 02:38:46  -Variants with bad EA: 0
2026/03/12 02:38:46  -Variants with bad NEA: 0
2026/03/12 02:38:46  -Variants with NA for EA or NEA: 0
2026/03/12 02:38:46  -Variants with same EA and NEA: 1950604
2026/03/12 02:38:59 Finished fixing alleles (EA and NEA).
2026/03/12 02:38:59 Start to perform sanity check for statistics ...(v4.0.4)
2026/03/12 02:38:59  -Comparison tolerance for floats: 1e-07
2026/03/12 02:39:01  -Checking if any columns are empty...
2026/03/12 02:39:07  -Checking if 0 <= N <= 2147483647 : removed 0 variants.
2026/03/12 02:39:09  -Checking if -1e-07 < EAF < 1.0000001 : removed 0 variants.
2026/03/12 02:39:09   -Examples of invalid variants(SNPID): 1:776572:C:T,1:819974:G:C,1:871173:C:T,1:871198:C:T,1:874451:C:T ...
2026/03/12 02:39:09   -Examples of invalid values (P): NA,NA,NA,NA,NA ...
2026/03/12 02:39:16  -Checking if -1e-07 < P < 1.0000001 : removed 1676 variants.
2026/03/12 02:39:16   -Examples of invalid variants(SNPID): 1:15791:C:T,1:877608:C:G,1:897032:A:G,1:899336:G:A,1:907676:A:T ...
2026/03/12 02:39:16   -Examples of invalid values (BETA): 894.616,279.71,-108.064,270.068,116.14 ...
2026/03/12 02:39:17  -Checking if -100.0000001 < BETA < 100.0000001 : removed 9906 variants.
2026/03/12 02:39:26  -Checking if -1e-07 < SE < inf : removed 0 variants.
2026/03/12 02:39:26  -Checking STATUS and converting STATUS to Int64....
2026/03/12 02:39:26  -Removed 11582 variants with bad statistics in total.
2026/03/12 02:39:26 Finished sanity check for statistics.
2026/03/12 02:39:26 Start to check data consistency across columns ...(v4.0.4)
2026/03/12 02:39:26  -Current Dataframe shape : 13779885 x 14 ; Memory usage: 1385.06 MB
2026/03/12 02:39:26  -Tolerance: 0.001 (Relative) and 0.001 (Absolute)
2026/03/12 02:39:26  -Checking if BETA/SE-derived-P is consistent with P...
2026/03/12 02:39:27   -Variants with inconsistent values were not detected.
2026/03/12 02:39:27   -Note: Minor differences are typically due to rounding.
2026/03/12 02:39:27    -If the max difference is greater than expected, please check your original sumstats.
2026/03/12 02:39:27 Finished checking data consistency across columns.
2026/03/12 02:39:27 Start to normalize indels ...(v4.0.4)
2026/03/12 02:39:27  -Number of threads/cores to use: 1
2026/03/12 02:39:27  -Number of variants to check:558
2026/03/12 02:39:27  -Chunk size:3000000
2026/03/12 02:39:27  -Processing in chunks:0
2026/03/12 02:39:28 Finished normalizing indels.
2026/03/12 02:39:28 Start to sort the genome coordinates ...(v4.0.4)
2026/03/12 02:39:40 Finished sorting coordinates.
2026/03/12 02:39:40 Start to reorder the columns ...(v4.0.4)
2026/03/12 02:39:40  -Reordering columns to    : SNPID,CHR,POS,EA,NEA,STATUS,EAF,BETA,SE,P,N,low_confidence_variant,AC,ytx
2026/03/12 02:39:40 Finished reordering the columns.

In [9]:
mysumstats.liftover(
    from_build="37",
    to_build="38",
    chain_path="/mnt/hdd_1/ofgeha/galaxy-gwas-tools/Gwaslab/hg19ToHg38.over.chain.gz",
    remove=True
)

2026/03/12 02:40:35 Start to perform liftover ...(v4.0.4)
2026/03/12 02:40:35  -Using provided chain file: /mnt/hdd_1/ofgeha/galaxy-gwas-tools/Gwaslab/hg19ToHg38.over.chain.gz
2026/03/12 02:40:47  -Converting variants with status code xxx0xxx: 13,779,885
2026/03/12 02:40:54  -Target build: 38
2026/03/12 02:40:54  -Input positions are 1-based
2026/03/12 02:40:54  -Output positions will be 1-based
2026/03/12 02:41:55  -Chromosome mismatches detected: 1896 variants (treated as unmapped)
2026/03/12 02:41:55  -Examples of chromosome mismatches:
2026/03/12 02:41:55    SNPID=1:13123419:T:A | CHR=1 | POS=13123419 | CHR_LIFT=1_KI270766v1_alt | POS_LIFT=1490 | STATUS=9960099
2026/03/12 02:41:55    SNPID=1:13123431:A:C | CHR=1 | POS=13123431 | CHR_LIFT=1_KI270766v1_alt | POS_LIFT=1502 | STATUS=9960099
2026/03/12 02:41:55    SNPID=1:13124908:G:A | CHR=1 | POS=13124908 | CHR_LIFT=1_KI270766v1_alt | POS_LIFT=2979 | STATUS=9960099
2026/03/12 02:41:55    SNPID=1:13125084:A:T | CHR=1 | POS=13125084 | CHR_LIFT=1_KI270766v1_alt | POS_LIFT=3155 | STATUS=9960099
2026/03/12 02:41:55    SNPID=1:13130561:T:C | CHR=1 | POS=13130561 | CHR_LIFT=1_KI270766v1_alt | POS_LIFT=8632 | STATUS=9960099
2026/03/12 02:41:55  -Mapped: 13771094 variants
2026/03/12 02:41:55  -Unmapped: 8791 variants
2026/03/12 02:41:55  -Examples of unmapped variants:
2026/03/12 02:41:55    SNPID=1:1581586:T:C | CHR=1 | POS=1581586 | STATUS=9960699
2026/03/12 02:41:55    SNPID=1:1584102:G:A | CHR=1 | POS=1584102 | STATUS=9960099
2026/03/12 02:41:55    SNPID=1:1584117:G:C | CHR=1 | POS=1584117 | STATUS=9960699
2026/03/12 02:41:55    SNPID=1:1584218:T:C | CHR=1 | POS=1584218 | STATUS=9960699
2026/03/12 02:41:55    SNPID=1:1584224:G:C | CHR=1 | POS=1584224 | STATUS=9960699
2026/03/12 02:42:14  -Removed 8791 unmapped variants
2026/03/12 02:42:14 Start to fix chromosome notation (CHR) ...(v4.0.4)
2026/03/12 02:42:14  -Current Dataframe shape : 13771094 x 14 ; Memory usage: 1371.05 MB
2026/03/12 02:42:14  -Checking CHR data type...
2026/03/12 02:42:14  -Variants with standardized chromosome notation: 13345276
2026/03/12 02:42:15  -Variants with fixable chromosome notations: 425818
2026/03/12 02:42:15  -No unrecognized chromosome notations...
2026/03/12 02:42:15  -Identifying non-autosomal chromosomes : X, Y, and MT ...
2026/03/12 02:42:15  -Identified 425818 variants on sex chromosomes...
2026/03/12 02:42:15  -Standardizing first sex chromosome chromosome notations: X to 23...
2026/03/12 02:42:17 Finished fixing chromosome notation (CHR).
2026/03/12 02:42:17 Start to fix basepair positions (POS) ...(v4.0.4)
2026/03/12 02:42:17  -Trying to convert datatype for POS: Int64 -> Int64...
2026/03/12 02:42:18  -Position bound:(0 , 250,000,000)
2026/03/12 02:42:18  -No outlier variants were removed.
2026/03/12 02:42:23  -Removed variants with bad positions: 0
2026/03/12 02:42:23 Finished fixing basepair positions (POS).
2026/03/12 02:42:24 Finished liftover.

In [ ]:
# 4. Now run Liftover
# Now that 'CHR' and 'POS' are physically in the index, liftover will find them.
# mysumstats.liftover(from_build="19", to_build="38")
# mysumstats.liftover(from_build="37", 
#                     to_build="38",
#                     remove=True)

In [10]:
mysumstats.data

,SNPID,CHR,POS,EA,NEA,STATUS,EAF,BETA,SE,P,N,low_confidence_variant,AC,ytx
0,1:69487:G:A,1,69487,A,G,3860099,0.000006,-2.715450,2.360060,0.249902,359983,True,4.15294,103.515
1,1:69569:T:C,1,69569,C,T,3860099,0.000188,-0.484284,0.423462,0.252778,359983,True,135.27800,3644.560
2,1:139853:C:T,1,139853,T,C,3860099,0.000006,-2.703560,2.360130,0.251997,359983,True,4.09020,101.840
3,1:692794:CA:C,1,757414,C,CA,3860399,0.110590,-0.016436,0.019585,0.401342,359983,False,79621.10000,2179000.000
4,1:693731:A:G,1,758351,G,A,3860099,0.115767,-0.004255,0.018507,0.818155,359983,False,83348.00000,2281760.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13779880,X:154929412:C:T,23,155699751,T,C,3860099,0.245473,-0.016260,0.010723,0.129427,359983,False,176732.00000,4837480.000
13779881,X:154929637:CT:C,23,155699976,C,CT,3860399,0.229726,-0.027098,0.011190,0.015456,359983,False,165395.00000,4525550.000
13779882,X:154929952:CAA:C,23,155700291,C,CAA,3860399,0.239430,-0.020494,0.011278,0.069202,359983,False,172381.00000,4717910.000
13779883,X:154930230:A:G,23,155700569,G,A,3860099,0.245887,-0.016347,0.010721,0.127334,359983,False,177030.00000,4845680.000
13779884,X:154930487:T:A,23,155700826,A,T,3860099,0.019559,0.007107,0.036783,0.846790,359983,False,14081.80000,385739.000

In [11]:
# Save to a gzipped TSV file
mysumstats.to_csv("/mnt/hdd_1/ofgeha/galaxy-gwas-tools/Data/21001_T2T_liftover.tsv.gz", 
                  sep="\t", 
                  index=False)