#### Harmonization

In [7]:
import gwaslab as gl

### Load test data

In [8]:
mysumstats = gl.Sumstats(
    "/mnt/hdd_1/ofgeha/galaxy-gwas-tools/Data/21001_T2T_liftover_rsid.tsv.gz",
    snpid="SNPID",
    chrom="CHR",
    pos="POS",
    ea="EA",            
    nea="NEA",          
    eaf="EAF",          
    beta="BETA",
    se="SE",
    p="P",
    verbose=True,
    readargs={'sep': '\t'}
)

2026/03/07 06:21:38 GWASLab v4.0.4 https://cloufield.github.io/gwaslab/
2026/03/07 06:21:38 (C) 2022-2026, Yunye He, Kamatani Lab, GPL-3.0 license, gwaslab@gmail.com
2026/03/07 06:21:38 Python version: 3.12.3 (main, Jan 22 2026, 20:57:42) [GCC 13.3.0]
2026/03/07 06:21:38 Start to initialize gl.Sumstats from file :/mnt/hdd_1/ofgeha/galaxy-gwas-tools/Data/21001_T2T_liftover_rsid.tsv.gz

2026/03/07 06:21:51  -Reading columns          : EA,SE,SNPID,CHR,P,NEA,POS,EAF,BETA
2026/03/07 06:21:51  -Renaming columns to      : EA,SE,SNPID,CHR,P,NEA,POS,EAF,BETA
2026/03/07 06:21:51  -Current Dataframe shape : 13779885  x  9
2026/03/07 06:21:51  -Initiating a status column: STATUS ...
2026/03/07 06:21:51 #WARNING! Version of genomic coordinates is unknown for homo sapiens (build: 99)...
2026/03/07 06:21:56 Start to reorder the columns ...(v4.0.4)
2026/03/07 06:21:56  -Reordering columns to    : SNPID,CHR,POS,EA,NEA,STATUS,EAF,BETA,SE,P
2026/03/07 06:21:59 Finished reordering the columns.
2026/03/07 06:21:59  -Trying to convert datatype for CHR: string -> Int64...Success
2026/03/07 06:21:59  -Column  : SNPID  CHR   POS   EA       NEA      STATUS EAF     BETA    SE      P
2026/03/07 06:21:59  -DType   : object Int64 int64 category category int64  float64 float64 float64 float64
2026/03/07 06:21:59  -Verified: T      T     T     T        T        T      T       T       T       T
2026/03/07 06:22:00  -Current Dataframe memory usage: 963.05 MB
2026/03/07 06:22:00 Finished loading data successfully!

In [9]:
mysumstats.data

,SNPID,CHR,POS,EA,NEA,STATUS,EAF,BETA,SE,P
0,1:69487:G:A,1,69487,A,G,9999999,0.999994,-2.715450,2.360060,0.249902
1,1:69569:T:C,1,69569,C,T,9999999,0.999812,-0.484284,0.423462,0.252778
2,1:139853:C:T,1,139853,T,C,9999999,0.999994,-2.703560,2.360130,0.251997
3,1:692794:CA:C,1,692794,C,CA,9999999,0.889410,-0.016436,0.019585,0.401342
4,1:693731:A:G,1,693731,G,A,9999999,0.884233,-0.004255,0.018507,0.818155
...,...,...,...,...,...,...,...,...,...,...
13779880,X:154929412:C:T,23,154929412,T,C,9999999,0.754527,-0.016260,0.010723,0.129427
13779881,X:154929637:CT:C,23,154929637,C,CT,9999999,0.770274,-0.027098,0.011190,0.015456
13779882,X:154929952:CAA:C,23,154929952,C,CAA,9999999,0.760570,-0.020494,0.011278,0.069202
13779883,X:154930230:A:G,23,154930230,G,A,9999999,0.754113,-0.016347,0.010721,0.127334
13779884,X:154930487:T:A,23,154930487,A,T,9999999,0.980441,0.007107,0.036783,0.846790

### Perform harmonization
 - ref_seq : reference genome fasta file for allele alignment
 - ref_infer : vcf file with allele frequency information for inferring strand and comparing allele frequency
 - ref_alt_freq : field in INFO of vcf file for alternative allele frequency

In [10]:
valid_bases = {'A', 'T', 'C', 'G'}
mysumstats.data = mysumstats.data[
    mysumstats.data["EA"].isin(valid_bases) & 
    mysumstats.data["NEA"].isin(valid_bases)
].copy()

mysumstats.data.attrs["build"] = "38"

mysumstats.harmonize(
    ref_seq="/mnt/hdd_1/ofgeha/galaxy-gwas-tools/Data/hg38.fa",
    ref_infer="/mnt/hdd_1/ofgeha/gwas-sumstats-harmoniser/gwas-ref/homo_sapiens-chr{chrom}.vcf.gz",
    ref_alt_freq="AF",
    threads=6,
    remove=True
)

2026/03/07 06:22:38 Start to check SNPID/rsID ...(v4.0.4)
2026/03/07 06:22:38  -Current Dataframe shape : 12641429 x 10 ; Memory usage: 980.24 MB
2026/03/07 06:22:38  -Checking SNPID data type...
2026/03/07 06:22:38  -Converted datatype for SNPID: object -> string
2026/03/07 06:22:38  -Checking if SNPID contains NA strings :na,NA,Na,Nan,NaN,<NA>,null,NULL,#N/A,#VALUE!,N/A,n/a,missing,...
2026/03/07 06:22:38  -Checking if SNPID is CHR:POS:NEA:EA...(separator: - ,: , _)
2026/03/07 06:22:43 Finished checking SNPID/rsID.
2026/03/07 06:22:43 Start to fix chromosome notation (CHR) ...(v4.0.4)
2026/03/07 06:22:43  -Checking CHR data type...
2026/03/07 06:22:45  -Variants with standardized chromosome notation: 12641429
2026/03/07 06:22:45  -All CHR are already fixed...
2026/03/07 06:22:46 Finished fixing chromosome notation (CHR).
2026/03/07 06:22:46 Start to fix basepair positions (POS) ...(v4.0.4)
2026/03/07 06:22:46  -Trying to convert datatype for POS: int64 -> Int64...
2026/03/07 06:22:47  -Position bound:(0 , 250,000,000)
2026/03/07 06:22:47  -No outlier variants were removed.
2026/03/07 06:22:52  -Removed variants with bad positions: 0
2026/03/07 06:22:52 Finished fixing basepair positions (POS).
2026/03/07 06:22:52 Start to fix alleles (EA and NEA) ...(v4.0.4)
2026/03/07 06:22:52  -Converted all bases to string datatype and UPPERCASE
2026/03/07 06:22:54  -Variants with bad EA: 0
2026/03/07 06:22:54  -Variants with bad NEA: 0
2026/03/07 06:22:54  -Variants with NA for EA or NEA: 0
2026/03/07 06:22:54  -Variants with same EA and NEA: 1810819
2026/03/07 06:23:00 Finished fixing alleles (EA and NEA).
2026/03/07 06:23:00 Start to perform sanity check for statistics ...(v4.0.4)
2026/03/07 06:23:00  -Comparison tolerance for floats: 1e-07
2026/03/07 06:23:00  -Checking if any columns are empty...
2026/03/07 06:23:03  -Checking if -1e-07 < EAF < 1.0000001 : removed 0 variants.
2026/03/07 06:23:05  -Checking if -1e-07 < P < 1.0000001 : removed 0 variants.
2026/03/07 06:23:07  -Checking if -100.0000001 < BETA < 100.0000001 : removed 0 variants.
2026/03/07 06:23:08  -Checking if -1e-07 < SE < inf : removed 0 variants.
2026/03/07 06:23:08  -Checking STATUS and converting STATUS to Int64....
2026/03/07 06:23:08  -No variants were removed with bad statistics in total.
2026/03/07 06:23:08 Finished sanity check for statistics.
2026/03/07 06:23:09 Start to normalize indels ...(v4.0.4)
2026/03/07 06:23:09  -Number of threads/cores to use: 6
2026/03/07 06:23:09  -No available variants to normalize..
2026/03/07 06:23:09 Finished normalizing indels.
2026/03/07 06:23:09 Start to reorder the columns ...(v4.0.4)
2026/03/07 06:23:09  -Reordering columns to    : SNPID,CHR,POS,EA,NEA,STATUS,EAF,BETA,SE,P
2026/03/07 06:23:09 Finished reordering the columns.
2026/03/07 06:23:09 Start to sort the genome coordinates ...(v4.0.4)
2026/03/07 06:23:15 Finished sorting coordinates.
2026/03/07 06:23:15 Start to check if NEA is aligned with reference sequence ...(v4.0.4)
2026/03/07 06:23:15  -Reference genome FASTA file: /mnt/hdd_1/ofgeha/galaxy-gwas-tools/Data/hg38.fa
2026/03/07 06:23:21    -Loading and building numpy fasta records:
2026/03/07 06:23:43  -Variants allele on given reference sequence :  0
2026/03/07 06:23:43  -Variants flipped :  0
2026/03/07 06:23:43   -Raw Matching rate :  0.00%
2026/03/07 06:23:43 #WARNING! Matching rate is low, please check if the right reference genome is used.
2026/03/07 06:23:43  -Variants inferred reverse_complement :  0
2026/03/07 06:23:43  -Variants inferred reverse_complement_flipped :  0
2026/03/07 06:23:43  -Both allele on genome + unable to distinguish :  0
2026/03/07 06:23:43  -Variants not on given reference sequence :  0
2026/03/07 06:23:43 Finished checking if NEA is aligned with reference sequence.
2026/03/07 06:23:43 Start to adjust statistics based on STATUS code ...(v4.0.4)
2026/03/07 06:23:44  -No statistics have been changed.
2026/03/07 06:23:44 Finished adjusting statistics based on STATUS code.
2026/03/07 06:23:44 Start to infer strand for palindromic SNPs/align indistinguishable indels ...(v4.0.4)
2026/03/07 06:23:44  -Number of threads/cores to use: 6
2026/03/07 06:23:44 #WARNING! Reference file not found: /mnt/hdd_1/ofgeha/gwas-sumstats-harmoniser/gwas-ref/homo_sapiens-chr{chrom}.vcf.gz. Using default format.
2026/03/07 06:23:44  -Field for alternative allele frequency in VCF INFO: AF
2026/03/07 06:23:44  -Identified  1660921  palindromic SNPs...
2026/03/07 06:23:45  -After filtering by MAF<= 0.4 , 0 palindromic SNPs with unknown strand will be inferred...
2026/03/07 06:23:45 #WARNING! No palindromic variants available for checking.
2026/03/07 06:23:45   -Non-palindromic :  9169689
2026/03/07 06:23:46   -Palindromic SNPs on + strand:  0
2026/03/07 06:23:47   -Palindromic SNPs on - strand and needed to be flipped: 0
2026/03/07 06:23:47   -Palindromic SNPs with MAF not available to infer :  86113
2026/03/07 06:23:48   -Palindromic SNPs lacking reference matches, or with reference ALT unavailable or above MAF threshold for inference :  0
2026/03/07 06:23:48  -Identified  0  indistinguishable Indels...
2026/03/07 06:23:48 #WARNING! No indistinguishable indels available for checking.
2026/03/07 06:23:48 Finished inferring strand for palindromic SNPs/align indistinguishable indels.
2026/03/07 06:23:48 Start to adjust statistics based on STATUS code ...(v4.0.4)
2026/03/07 06:23:48  -No statistics have been changed.
2026/03/07 06:23:48 Finished adjusting statistics based on STATUS code.
2026/03/07 06:23:49 Start to remove duplicated/multiallelic variants ...(v4.0.4)
2026/03/07 06:23:49  -Removing mode:dm
2026/03/07 06:23:49 Start to sort the sumstats using P ...
2026/03/07 06:23:51 Start to remove duplicated variants based on snpid ...(v4.0.4)
2026/03/07 06:23:51  -Which variant to keep:  first
2026/03/07 06:24:01  -Removed variants based on SNPID: 0
2026/03/07 06:24:01 Start to remove duplicated variants based on CHR,POS,EA and NEA ...
2026/03/07 06:24:01  -Which variant to keep:  first
2026/03/07 06:24:09  -Removed variants based on CHR,POS,EA and NEA: 705
2026/03/07 06:24:09 Start to remove multiallelic variants based on chr:pos ...
2026/03/07 06:24:09  -Current Dataframe shape : 12640724 x 10 ; Memory usage: 880.03 MB
2026/03/07 06:24:09  -Which variant to keep:  first
2026/03/07 06:24:16  -Removed variants multiallelic variants: 8853
2026/03/07 06:24:16  -Removed variants in total: 9558
2026/03/07 06:24:16  -Sort the coordinates based on CHR and POS...
2026/03/07 06:24:25 Finished removing duplicated/multiallelic variants.
2026/03/07 06:24:25 Start to sort the genome coordinates ...(v4.0.4)
2026/03/07 06:24:31 Finished sorting coordinates.
2026/03/07 06:24:31 Start to reorder the columns ...(v4.0.4)
2026/03/07 06:24:31  -Reordering columns to    : SNPID,CHR,POS,EA,NEA,STATUS,EAF,BETA,SE,P
2026/03/07 06:24:31 Finished reordering the columns.


All variants were checked and harmonized based on the reference datasets. The manipulations are reflected in STATUS column.

In [5]:
mysumstats.data

,SNPID,CHR,POS,EA,NEA,STATUS,EAF,BETA,SE,P
0,1:69487:G:A,1,69487,A,G,9960090,0.999994,-2.715450,2.360060,0.249902
1,1:69569:T:C,1,69569,C,T,9960090,0.999812,-0.484284,0.423462,0.252778
2,1:139853:C:T,1,139853,T,C,9960090,0.999994,-2.703560,2.360130,0.251997
3,1:693731:A:G,1,693731,G,A,9960090,0.884233,-0.004255,0.018507,0.818155
4,1:707522:G:C,1,707522,C,G,9960099,0.902745,-0.010428,0.020804,0.616190
...,...,...,...,...,...,...,...,...,...,...
12631866,X:154925895:C:T,23,154925895,T,C,9960090,0.758067,-0.019349,0.010966,0.077653
12631867,X:154927581:G:A,23,154927581,A,G,9960090,0.697822,-0.012985,0.010082,0.197734
12631868,X:154929412:C:T,23,154929412,T,C,9960090,0.754527,-0.016260,0.010723,0.129427
12631869,X:154930230:A:G,23,154930230,G,A,9960090,0.754113,-0.016347,0.010721,0.127334
12631870,X:154930487:T:A,23,154930487,A,T,9960099,0.980441,0.007107,0.036783,0.846790

### Check summary

In [6]:
mysumstats.summary()

{'overview': {'Row_num': '12631871',
  'Column_num': '10',
  'Column_names': 'SNPID,CHR,POS,EA,NEA,STATUS,EAF,BETA,SE,P',
  'Last_checked_time': 'Sun Feb  8 14:07:48 2026',
  'QC and Harmonization': {'basic_check': {'performed': True,
    'last_executed': '2026-02-08 14:05:21',
    'parameters_used': {'basic_check': True,
     'ref_seq': '/mnt/hdd_1/ofgeha/galaxy-gwas-tools/Data/hg38.fa',
     'ref_rsid_tsv': None,
     'ref_rsid_vcf': None,
     'ref_infer': '/mnt/hdd_1/ofgeha/gwas-sumstats-harmoniser/gwas-ref/homo_sapiens-chr{chrom}.vcf.gz',
     'ref_alt_freq': 'AF',
     'ref_maf_threshold': 0.4,
     'maf_threshold': 0.4,
     'threads': 6,
     'remove': True,
     'check_ref_kwargs': {},
     'remove_dup_kwargs': {},
     'assign_rsid_kwargs': {},
     'infer_strand_kwargs': {},
     'flip_allele_stats_kwargs': {},
     'liftover_kwargs': {},
     'fix_id_kwargs': {},
     'fix_chr_kwargs': {},
     'fix_pos_kwargs': {},
     'fix_allele_kwargs': {},
     'sanity_check_stats_kwargs': {},
     'normalize_allele_kwargs': {},
     'verbose': True,
     'sweep_mode': False}},
   'harmonize': {'performed': True,
    'last_executed': '2026-02-08 14:06:47',
    'parameters_used': {'basic_check': True,
     'ref_seq': '/mnt/hdd_1/ofgeha/galaxy-gwas-tools/Data/hg38.fa',
     'ref_rsid_tsv': None,
     'ref_rsid_vcf': None,
     'ref_infer': '/mnt/hdd_1/ofgeha/gwas-sumstats-harmoniser/gwas-ref/homo_sapiens-chr{chrom}.vcf.gz',
     'ref_alt_freq': 'AF',
     'ref_maf_threshold': 0.4,
     'maf_threshold': 0.4,
     'threads': 6,
     'remove': True,
     'check_ref_kwargs': {},
     'remove_dup_kwargs': {},
     'assign_rsid_kwargs': {},
     'infer_strand_kwargs': {},
     'flip_allele_stats_kwargs': {},
     'liftover_kwargs': {},
     'fix_id_kwargs': {},
     'fix_chr_kwargs': {},
     'fix_pos_kwargs': {},
     'fix_allele_kwargs': {},
     'sanity_check_stats_kwargs': {},
     'normalize_allele_kwargs': {},
     'verbose': True,
     'sweep_mode': False}},
   'qc_and_harmonization_status': {'qc': {'id': {'performed': True,
      'last_executed': '2026-02-08 14:05:21',
      'parameters_used': {}},
     'chr': {'performed': True,
      'last_executed': '2026-02-08 14:05:21',
      'parameters_used': {}},
     'pos': {'performed': True,
      'last_executed': '2026-02-08 14:05:21',
      'parameters_used': {}},
     'allele': {'performed': True,
      'last_executed': '2026-02-08 14:05:21',
      'parameters_used': {}},
     'sanity': {'performed': True,
      'last_executed': '2026-02-08 14:05:21',
      'parameters_used': {}},
     'consistency': {'performed': True,
      'last_executed': '2026-02-08 14:05:21',
      'parameters_used': {}},
     'normalize': {'performed': False,
      'last_executed': '',
      'parameters_used': {}},
     'remove_dup': {'performed': True,
      'last_executed': '2026-02-08 14:06:41',
      'parameters_used': {'mode': 'dm',
       'chrom': 'CHR',
       'pos': 'POS',
       'snpid': 'SNPID',
       'ea': 'EA',
       'nea': 'NEA',
       'rsid': 'rsID',
       'keep': 'first',
       'keep_col': 'P',
       'remove_na': False,
       'keep_ascend': True}},
     'sort_coord': {'performed': True,
      'last_executed': '2026-02-08 14:06:47',
      'parameters_used': {'chrom': 'CHR', 'pos': 'POS', 'reindex': True}},
     'sort_column': {'performed': True,
      'last_executed': '2026-02-08 14:06:47',
      'parameters_used': {'order': ['SNPID',
        'rsID',
        'CHR',
        'POS',
        'EA',
        'NEA',
        'STATUS',
        'REF',
        'ALT',
        'EAF',
        'RAF',
        'NEAF',
        'MAF',
        'DAF',
        'INFO',
        'BETA',
        'SE',
        'BETA_95U',
        'BETA_95L',
        'OR',
        'OR_95U',
        'OR_95L',
        'HR',
        'HR_95U',
        'HR_95L',
        'CHISQ',
        'Z',
        'T',
        'F',
        'P',
        'P_MANTISSA',
        'P_EXPONENT',
        'MLOG10P',
        'SNPR2',
        'DOF',
        'P_HET',
        'I2_HET',
        'I2',
        'DIRECTION',
        'DENSITY',
        'N',
        'N_CASE',
        'N_CONTROL',
        'N_EFF',
        'GENENAME',
        'CIS/TRANS',
        'DISTANCE_TO_KNOWN',
        'LOCATION_OF_KNOWN',
        'KNOWN_ID',
        'KNOWN_PUBMED_ID',
        'KNOWN_AUTHOR',
        'KNOWN_SET_VARIANT',
        'KNOWN_VARIANT',
        'KNOWN_SET',
        'NOVEL',
        'PIP',
        'CREDIBLE_SET_INDEX',
        'N_SNP',
        'LOCUS',
        'STUDY',
        'TEST',
        'BETA_RANDOM',
        'SE_RANDOM',
        'Z_RANDOM',
        'P_RANDOM']}}},
    'harmonize': {'check_ref': {'performed': True,
      'last_executed': '2026-02-08 14:06:47',
      'parameters_used': {}},
     'flip_allele_stats': {'performed': True,
      'last_executed': '2026-02-08 14:06:47',
      'parameters_used': {}},
     'infer_strand': {'performed': True,
      'last_executed': '2026-02-08 14:06:47',
      'parameters_used': {}},
     'assign_rsid': {'performed': False,
      'last_executed': '',
      'parameters_used': {}},
     'liftover': {'performed': False,
      'last_executed': '',
      'parameters_used': {}}}}}},
 'chromosomes': {'Chromosomes_notations': [1,
   2,
   3,
   4,
   5,
   6,
   7,
   8,
   9,
   10,
   11,
   12,
   13,
   14,
   15,
   16,
   17,
   18,
   19,
   20,
   21,
   22,
   23],
  'Chromosomes_numbers': 23,
  'chr1': 956723,
  'chr2': 1039127,
  'chr3': 877890,
  'chr4': 886991,
  'chr5': 799667,
  'chr6': 814966,
  'chr7': 717584,
  'chr8': 685433,
  'chr9': 534786,
  'chr10': 621526,
  'chr11': 613862,
  'chr12': 577765,
  'chr13': 437372,
  'chr14': 392787,
  'chr15': 345667,
  'chr16': 385609,
  'chr17': 330467,
  'chr18': 342514,
  'chr19': 280649,
  'chr20': 271457,
  'chr21': 163170,
  'chr22': 164185,
  'chr23': 391674,
  'Chromosomes_numbers percentage': 1.8207912351226513e-06,
  'chr1 percentage': 0.07573881968870645,
  'chr2 percentage': 0.08226231885996936,
  'chr3 percentage': 0.0694980181479054,
  'chr4 percentage': 0.07021849732315981,
  'chr5 percentage': 0.06330550715725326,
  'chr6 percentage': 0.06451664998795507,
  'chr7 percentage': 0.05680741989844577,
  'chr8 percentage': 0.05426219124625323,
  'chr9 percentage': 0.042336246150708794,
  'chr10 percentage': 0.049203004052210474,
  'chr11 percentage': 0.04859628474673308,
  'chr12 percentage': 0.045738671650462547,
  'chr13 percentage': 0.03462448278643757,
  'chr14 percentage': 0.03109491855957047,
  'chr15 percentage': 0.027364671472658326,
  'chr16 percentage': 0.030526673364539583,
  'chr17 percentage': 0.026161365960751182,
  'chr18 percentage': 0.027115064743773905,
  'chr19 percentage': 0.02221753214547552,
  'chr20 percentage': 0.021489848970116937,
  'chr21 percentage': 0.012917326340650565,
  'chr22 percentage': 0.012997678649504891,
  'chr23 percentage': 0.031006808096757797},
 'missing_values': {'Missing_total': 0, 'Missing_total percentage': 0.0},
 'MAF': {'Common (MAF>=0.05)': 6212666,
  'Low_frequency (0.01<MAF<=0.05)': 2497962,
  'Rare (0.001<MAF<=0.01)': 3731173,
  'Ultra Rare (MAF<=0.001)': 190070,
  'Common (MAF>=0.05) percentage': 0.49182468693671744,
  'Low_frequency (0.01<MAF<=0.05) percentage': 0.1977507528378021,
  'Rare (0.001<MAF<=0.01) percentage': 0.29537769978809947,
  'Ultra Rare (MAF<=0.001) percentage': 0.01504686043738097},
 'p_values': {'Minimum': 5.4652e-220,
  'P<5e-8': 46291,
  'P<5e-6': 102733,
  'P<5e-8 percentage': 0.0036646194376114194,
  'P<5e-6 percentage': 0.008132841128602407},
 'beta_for_significant_variants': {'P<5e-8 with ABS(BETA)>10': 11,
  'P<5e-8 with ABS(BETA)>3': 11,
  'P<5e-8 with ABS(BETA)>1': 11,
  'P<5e-8 with ABS(BETA)>0.5': 64,
  'P<5e-8 with ABS(BETA)>0.3': 245,
  'P<5e-8 with ABS(BETA)>0.2': 754,
  'P<5e-8 with ABS(BETA)>0.1': 9970,
  'P<5e-8 with ABS(BETA)>0.05': 46291,
  'P<5e-8 with ABS(BETA)>10 percentage': 8.708131994064854e-07,
  'P<5e-8 with ABS(BETA)>3 percentage': 8.708131994064854e-07,
  'P<5e-8 with ABS(BETA)>1 percentage': 8.708131994064854e-07,
  'P<5e-8 with ABS(BETA)>0.5 percentage': 5.066549523819552e-06,
  'P<5e-8 with ABS(BETA)>0.3 percentage': 1.939538489587172e-05,
  'P<5e-8 with ABS(BETA)>0.2 percentage': 5.969028657749909e-05,
  'P<5e-8 with ABS(BETA)>0.1 percentage': 0.0007892734180075145,
  'P<5e-8 with ABS(BETA)>0.05 percentage': 0.0036646194376114194},
 'variant_status': {'9960090': {'count': 9164042,
   'explanation': {'Genome_Build': 'Unchecked',
    'rsID&SNPID': 'rsid unknown & SNPID valid',
    'CHR&POS': 'CHR valid & POS valid',
    'Stadardize&Normalize': 'standardized SNP',
    'Align': 'Unchecked',
    'Panlidromic_SNP&Indel': 'Not_palindromic_SNPs'}},
  '9960699': {'count': 1809229,
   'explanation': {'Genome_Build': 'Unchecked',
    'rsID&SNPID': 'rsid unknown & SNPID valid',
    'CHR&POS': 'CHR valid & POS valid',
    'Stadardize&Normalize': 'invalid allele notation',
    'Align': 'Unchecked',
    'Panlidromic_SNP&Indel': 'Unchecked'}},
  '9960099': {'count': 1572545,
   'explanation': {'Genome_Build': 'Unchecked',
    'rsID&SNPID': 'rsid unknown & SNPID valid',
    'CHR&POS': 'CHR valid & POS valid',
    'Stadardize&Normalize': 'standardized SNP',
    'Align': 'Unchecked',
    'Panlidromic_SNP&Indel': 'Unchecked'}},
  '9960097': {'count': 86055,
   'explanation': {'Genome_Build': 'Unchecked',
    'rsID&SNPID': 'rsid unknown & SNPID valid',
    'CHR&POS': 'CHR valid & POS valid',
    'Stadardize&Normalize': 'standardized SNP',
    'Align': 'Unchecked',
    'Panlidromic_SNP&Indel': 'Indistinguishable'}}},
 'variants': {'variant_number': 12631871,
  'min_P': 5.4652e-220,
  'min_minor_allele_freq': 0.0}}

In [7]:
mysumstats.lookup_status()

,Genome_Build,rsID&SNPID,CHR&POS,Stadardize&Normalize,Align,Panlidromic_SNP&Indel,Count,Percentage(%)
9960090,Unchecked,rsid unknown & SNPID valid,CHR valid & POS valid,standardized SNP,Unchecked,Not_palindromic_SNPs,9164042,72.55
9960097,Unchecked,rsid unknown & SNPID valid,CHR valid & POS valid,standardized SNP,Unchecked,Indistinguishable,86055,0.68
9960099,Unchecked,rsid unknown & SNPID valid,CHR valid & POS valid,standardized SNP,Unchecked,Unchecked,1572545,12.45
9960699,Unchecked,rsid unknown & SNPID valid,CHR valid & POS valid,invalid allele notation,Unchecked,Unchecked,1809229,14.32