In [1]:
import gwaslab as gl

In [8]:
mysumstats = gl.Sumstats(
    "/mnt/hdd_1/ofgeha/galaxy-gwas-tools/Data/21001_raw.gwas.imputed_v3.both_sexes.tsv.bgz",
    snpid="SNPID",
    chrom="CHR",
    pos="POS",
    ea="EA",            
    nea="NEA",          
    eaf="EAF",          
    beta="BETA",
    se="SE",
    p="P",
    verbose=True,
    readargs={'sep': '\t'}
)

In [3]:
mysumstats.data

In [7]:
# valid_bases = {'A', 'T', 'C', 'G'}
# mysumstats.data = mysumstats.data[
#     mysumstats.data["EA"].isin(valid_bases) & 
#     mysumstats.data["NEA"].isin(valid_bases)
# ].copy()

mysumstats.data.attrs["build"] = "38"

mysumstats.harmonize(
    ref_seq="/mnt/hdd_1/ofgeha/galaxy-gwas-tools/Data/hg38.fa",
    ref_infer="/mnt/hdd_1/ofgeha/gwas-sumstats-harmoniser/gwas-ref/homo_sapiens-chr*.vcf.gz",
    ref_alt_freq="AF",
    threads=6,
    remove=True
)

In [ ]:
mysumstats.liftover(from_build="19", to_build="38")

In [2]:
import gwaslab as gl
mysumstats = gl.Sumstats(
    "/mnt/hdd_1/ofgeha/gwas-sumstats-harmoniser/Data/21001_raw.gwas.imputed_v3.both_sexes.tsv",
    fmt="auto")

In [3]:
mysumstats.data

In [4]:
mysumstats.columns

In [1]:
import gwaslab as gl
import pandas as pd

In [2]:
mysumstats = gl.Sumstats(
    "/mnt/hdd_1/ofgeha/gwas-sumstats-harmoniser/Data/21001_raw.gwas.imputed_v3.both_sexes.tsv",
    snpid="variant",
    ea="minor_allele",
    eaf="minor_AF",
    beta="beta",
    se="se",
    p="pval",
    n="n_complete_samples",
    other=["low_confidence_variant", "AC", "ytx"]
)

2026/03/12 03:16:09 GWASLab v4.0.4 https://cloufield.github.io/gwaslab/
2026/03/12 03:16:09 (C) 2022-2026, Yunye He, Kamatani Lab, GPL-3.0 license, gwaslab@gmail.com
2026/03/12 03:16:09 Python version: 3.12.3 (main, Mar  3 2026, 12:15:18) [GCC 13.3.0]
2026/03/12 03:16:09 Start to initialize gl.Sumstats from file :/mnt/hdd_1/ofgeha/gwas-sumstats-harmoniser/Data/21001_raw.gwas.imputed_v3.both_sexes.tsv
2026/03/12 03:16:25  -Reading columns          : minor_allele,AC,beta,se,low_confidence_variant,pval,n_complete_samples,ytx,minor_AF,variant
2026/03/12 03:16:25  -Renaming columns to      : EA,AC,BETA,SE,low_confidence_variant,P,N,ytx,EAF,SNPID
2026/03/12 03:16:25  -Current Dataframe shape : 13791467  x  10
2026/03/12 03:16:25  -Initiating a status column: STATUS ...
2026/03/12 03:16:25 #WARNING! Version of genomic coordinates is unknown for homo sapiens (build: 99)...
2026/03/12 03:16:26 Start to reorder the columns ...(v4.0.4)
2026/03/12 03:16:26  -Reordering columns to    : SNPID,EA,STATUS,EAF,BETA,SE,P,N,low_confidence_variant,AC,ytx
2026/03/12 03:16:27 Finished reordering the columns.
2026/03/12 03:16:27  -Column  : SNPID  EA       STATUS EAF     BETA    SE      P       N     low_confidence_variant AC      ytx
2026/03/12 03:16:27  -DType   : object category int64  float64 float64 float64 float64 int64 bool                   float64 float64
2026/03/12 03:16:27  -Verified: T      T        T      T       T       T       T       T     NA                     NA      NA
2026/03/12 03:16:27  -Current Dataframe memory usage: 1014.01 MB
2026/03/12 03:16:27 Finished loading data successfully!

In [3]:
mysumstats.data

,SNPID,EA,STATUS,EAF,BETA,SE,P,N,low_confidence_variant,AC,ytx
0,1:15791:C:T,T,9999999,5.446880e-09,894.616000,1204.870000,0.457786,359983,True,0.003922,1.238950e-01
1,1:69487:G:A,A,9999999,5.768250e-06,-2.715450,2.360060,0.249902,359983,True,4.152940,1.035150e+02
2,1:69569:T:C,C,9999999,1.878960e-04,-0.484284,0.423462,0.252778,359983,True,135.278000,3.644560e+03
3,1:139853:C:T,T,9999999,5.681100e-06,-2.703560,2.360130,0.251997,359983,True,4.090200,1.018400e+02
4,1:692794:CA:C,C,9999999,1.105900e-01,-0.016436,0.019585,0.401342,359983,False,79621.100000,2.179000e+06
...,...,...,...,...,...,...,...,...,...,...,...
13791462,X:154929412:C:T,T,9999999,2.454730e-01,-0.016260,0.010723,0.129427,359983,False,176732.000000,4.837480e+06
13791463,X:154929637:CT:C,C,9999999,2.297260e-01,-0.027098,0.011190,0.015456,359983,False,165395.000000,4.525550e+06
13791464,X:154929952:CAA:C,C,9999999,2.394300e-01,-0.020494,0.011278,0.069202,359983,False,172381.000000,4.717910e+06
13791465,X:154930230:A:G,G,9999999,2.458870e-01,-0.016347,0.010721,0.127334,359983,False,177030.000000,4.845680e+06
13791466,X:154930487:T:A,A,9999999,1.955900e-02,0.007107,0.036783,0.846790,359983,False,14081.800000,3.857390e+05

In [5]:
# download references
print(gl.get_path("hg19"))
print(gl.get_path("1kg_dbsnp151_hg19_auto"))
print(gl.get_path("1kg_eur_hg19"))

2026/03/12 03:17:15 No records in config file. Please download first.
False
/home/ofgeha/.gwaslab/1kg_dbsnp151_hg19_auto.txt.gz
2026/03/12 03:17:15 No records in config file. Please download first.
False

In [6]:
mysumstats.basic_check()

2026/03/12 03:17:34 Start to check SNPID/rsID ...(v4.0.4)
2026/03/12 03:17:34  -Checking SNPID data type...
2026/03/12 03:17:34  -Checking if SNPID contains NA strings :na,NA,Na,Nan,NaN,<NA>,null,NULL,#N/A,#VALUE!,N/A,n/a,missing,...
2026/03/12 03:17:34  -Checking if SNPID is CHR:POS:NEA:EA...(separator: - ,: , _)
2026/03/12 03:17:50 Finished checking SNPID/rsID.
2026/03/12 03:17:50 Start to fix chromosome notation (CHR) ...(v4.0.4)
2026/03/12 03:17:50 #WARNING! Necessary columns for .fix_chr() were not detected:CHR
2026/03/12 03:17:50 Start to fix basepair positions (POS) ...(v4.0.4)
2026/03/12 03:17:50 #WARNING! Necessary columns for .fix_pos() were not detected:POS
2026/03/12 03:17:50 Start to fix alleles (EA and NEA) ...(v4.0.4)
2026/03/12 03:17:50 #WARNING! Necessary columns for .fix_allele() were not detected:NEA
2026/03/12 03:17:50 Start to perform sanity check for statistics ...(v4.0.4)
2026/03/12 03:17:50  -Comparison tolerance for floats: 1e-07
2026/03/12 03:17:56  -Checking if any columns are empty...
2026/03/12 03:18:05  -Checking if 0 <= N <= 2147483647 : removed 0 variants.
2026/03/12 03:18:11  -Checking if -1e-07 < EAF < 1.0000001 : removed 0 variants.
2026/03/12 03:18:13   -Examples of invalid variants(SNPID): 1:776572:C:T,1:819974:G:C,1:871173:C:T,1:871198:C:T,1:874451:C:T ...
2026/03/12 03:18:13   -Examples of invalid values (P): NA,NA,NA,NA,NA ...
2026/03/12 03:18:19  -Checking if -1e-07 < P < 1.0000001 : removed 1676 variants.
2026/03/12 03:18:20   -Examples of invalid variants(SNPID): 1:15791:C:T,1:877608:C:G,1:897032:A:G,1:899336:G:A,1:907676:A:T ...
2026/03/12 03:18:20   -Examples of invalid values (BETA): 894.616,279.71,-108.064,270.068,116.14 ...
2026/03/12 03:18:25  -Checking if -100.0000001 < BETA < 100.0000001 : removed 9906 variants.
2026/03/12 03:18:32  -Checking if -1e-07 < SE < inf : removed 0 variants.
2026/03/12 03:18:32  -Checking STATUS and converting STATUS to Int64....
2026/03/12 03:18:33  -Removed 11582 variants with bad statistics in total.
2026/03/12 03:18:33 Finished sanity check for statistics.
2026/03/12 03:18:33 Start to check data consistency across columns ...(v4.0.4)
2026/03/12 03:18:33  -Current Dataframe shape : 13779885 x 11 ; Memory usage: 1092.01 MB
2026/03/12 03:18:33  -Tolerance: 0.001 (Relative) and 0.001 (Absolute)
2026/03/12 03:18:33  -Checking if BETA/SE-derived-P is consistent with P...
2026/03/12 03:18:45   -Variants with inconsistent values were not detected.
2026/03/12 03:18:45   -Note: Minor differences are typically due to rounding.
2026/03/12 03:18:45    -If the max difference is greater than expected, please check your original sumstats.
2026/03/12 03:18:45 Finished checking data consistency across columns.
2026/03/12 03:18:45 Start to normalize indels ...(v4.0.4)
2026/03/12 03:18:45  -Number of threads/cores to use: 1
2026/03/12 03:18:45 #WARNING! Necessary columns for .normalize() were not detected:NEA
2026/03/12 03:18:45 Start to sort the genome coordinates ...(v4.0.4)
2026/03/12 03:18:45 #WARNING! Necessary columns for .sort_coordinate() were not detected:CHR,POS
2026/03/12 03:18:45 Start to reorder the columns ...(v4.0.4)
2026/03/12 03:18:45  -Reordering columns to    : SNPID,EA,STATUS,EAF,BETA,SE,P,N,low_confidence_variant,AC,ytx
2026/03/12 03:18:48 Finished reordering the columns.

In [7]:
mysumstats.harmonize(
    ref_seq=gl.get_path("hg19"),
    ref_rsid_tsv=gl.get_path("1kg_dbsnp151_hg19_auto"),
    ref_infer=gl.get_path("1kg_eur_hg19"),
    ref_alt_freq="AF",
    threads=4
)

2026/03/12 03:19:11 No records in config file. Please download first.
2026/03/12 03:19:11 No records in config file. Please download first.
2026/03/12 03:19:11 Start to check SNPID/rsID ...(v4.0.4)
2026/03/12 03:19:11  -Checking SNPID data type...
2026/03/12 03:19:11  -Checking if SNPID contains NA strings :na,NA,Na,Nan,NaN,<NA>,null,NULL,#N/A,#VALUE!,N/A,n/a,missing,...
2026/03/12 03:19:11  -Checking if SNPID is CHR:POS:NEA:EA...(separator: - ,: , _)
2026/03/12 03:19:26 Finished checking SNPID/rsID.
2026/03/12 03:19:26 Start to fix chromosome notation (CHR) ...(v4.0.4)
2026/03/12 03:19:26 #WARNING! Necessary columns for .fix_chr() were not detected:CHR
2026/03/12 03:19:26 Start to fix basepair positions (POS) ...(v4.0.4)
2026/03/12 03:19:26 #WARNING! Necessary columns for .fix_pos() were not detected:POS
2026/03/12 03:19:26 Start to fix alleles (EA and NEA) ...(v4.0.4)
2026/03/12 03:19:26 #WARNING! Necessary columns for .fix_allele() were not detected:NEA
2026/03/12 03:19:26 Start to perform sanity check for statistics ...(v4.0.4)
2026/03/12 03:19:26  -Comparison tolerance for floats: 1e-07
2026/03/12 03:19:35  -Checking if any columns are empty...
2026/03/12 03:19:44  -Checking if 0 <= N <= 2147483647 : removed 0 variants.
2026/03/12 03:19:49  -Checking if -1e-07 < EAF < 1.0000001 : removed 0 variants.
2026/03/12 03:19:57  -Checking if -1e-07 < P < 1.0000001 : removed 0 variants.
2026/03/12 03:20:03  -Checking if -100.0000001 < BETA < 100.0000001 : removed 0 variants.
2026/03/12 03:20:09  -Checking if -1e-07 < SE < inf : removed 0 variants.
2026/03/12 03:20:09  -Checking STATUS and converting STATUS to Int64....
2026/03/12 03:20:09  -No variants were removed with bad statistics in total.
2026/03/12 03:20:09 Finished sanity check for statistics.
2026/03/12 03:20:09 Start to normalize indels ...(v4.0.4)
2026/03/12 03:20:09  -Number of threads/cores to use: 4
2026/03/12 03:20:09 #WARNING! Necessary columns for .normalize() were not detected:NEA
2026/03/12 03:20:09 Start to reorder the columns ...(v4.0.4)
2026/03/12 03:20:09  -Reordering columns to    : SNPID,EA,STATUS,EAF,BETA,SE,P,N,low_confidence_variant,AC,ytx
2026/03/12 03:20:13 Finished reordering the columns.
2026/03/12 03:20:14 Start to sort the genome coordinates ...(v4.0.4)
2026/03/12 03:20:14 #WARNING! Necessary columns for .sort_coordinate() were not detected:CHR,POS
2026/03/12 03:20:14 Start to check if NEA is aligned with reference sequence ...(v4.0.4)
2026/03/12 03:20:14 #WARNING! Necessary columns for .check_ref() were not detected:CHR,POS,NEA
2026/03/12 03:20:14 Start to adjust statistics based on STATUS code ...(v4.0.4)

RecursionError: maximum recursion depth exceeded