In [1]:
import gwaslab as gl

In [8]:
mysumstats = gl.Sumstats(
    "/mnt/hdd_1/ofgeha/galaxy-gwas-tools/Data/21001_raw.gwas.imputed_v3.both_sexes.tsv.bgz",
    snpid="SNPID",
    chrom="CHR",
    pos="POS",
    ea="EA",            
    nea="NEA",          
    eaf="EAF",          
    beta="BETA",
    se="SE",
    p="P",
    verbose=True,
    readargs={'sep': '\t'}
)

2026/03/07 06:28:13 GWASLab v4.0.4 https://cloufield.github.io/gwaslab/
2026/03/07 06:28:13 (C) 2022-2026, Yunye He, Kamatani Lab, GPL-3.0 license, gwaslab@gmail.com
2026/03/07 06:28:13 Python version: 3.12.3 (main, Jan 22 2026, 20:57:42) [GCC 13.3.0]

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

In [3]:
mysumstats.data

,SNPID,CHR,POS,EA,NEA,STATUS,EAF,BETA,SE,P
0,1:69487:G:A,1,69487,A,G,9999999,0.999994,-2.715450,2.360060,0.249902
1,1:69569:T:C,1,69569,C,T,9999999,0.999812,-0.484284,0.423462,0.252778
2,1:139853:C:T,1,139853,T,C,9999999,0.999994,-2.703560,2.360130,0.251997
3,1:692794:CA:C,1,692794,C,CA,9999999,0.889410,-0.016436,0.019585,0.401342
4,1:693731:A:G,1,693731,G,A,9999999,0.884233,-0.004255,0.018507,0.818155
...,...,...,...,...,...,...,...,...,...,...
13779880,X:154929412:C:T,23,154929412,T,C,9999999,0.754527,-0.016260,0.010723,0.129427
13779881,X:154929637:CT:C,23,154929637,C,CT,9999999,0.770274,-0.027098,0.011190,0.015456
13779882,X:154929952:CAA:C,23,154929952,C,CAA,9999999,0.760570,-0.020494,0.011278,0.069202
13779883,X:154930230:A:G,23,154930230,G,A,9999999,0.754113,-0.016347,0.010721,0.127334
13779884,X:154930487:T:A,23,154930487,A,T,9999999,0.980441,0.007107,0.036783,0.846790

In [7]:
# valid_bases = {'A', 'T', 'C', 'G'}
# mysumstats.data = mysumstats.data[
#     mysumstats.data["EA"].isin(valid_bases) & 
#     mysumstats.data["NEA"].isin(valid_bases)
# ].copy()

mysumstats.data.attrs["build"] = "38"

mysumstats.harmonize(
    ref_seq="/mnt/hdd_1/ofgeha/galaxy-gwas-tools/Data/hg38.fa",
    ref_infer="/mnt/hdd_1/ofgeha/gwas-sumstats-harmoniser/gwas-ref/homo_sapiens-chr*.vcf.gz",
    ref_alt_freq="AF",
    threads=6,
    remove=True
)

2026/03/07 06:24:23 Start to check SNPID/rsID ...(v4.0.4)
2026/03/07 06:24:23  -Checking SNPID data type...
2026/03/07 06:24:23  -Checking if SNPID contains NA strings :na,NA,Na,Nan,NaN,<NA>,null,NULL,#N/A,#VALUE!,N/A,n/a,missing,...
2026/03/07 06:24:24  -Checking if SNPID is CHR:POS:NEA:EA...(separator: - ,: , _)
2026/03/07 06:24:28 Finished checking SNPID/rsID.
2026/03/07 06:24:28 Start to fix chromosome notation (CHR) ...(v4.0.4)
2026/03/07 06:24:28  -Checking CHR data type...
2026/03/07 06:24:31  -Variants with standardized chromosome notation: 13779885
2026/03/07 06:24:31  -All CHR are already fixed...
2026/03/07 06:24:32 Finished fixing chromosome notation (CHR).
2026/03/07 06:24:32 Start to fix basepair positions (POS) ...(v4.0.4)
2026/03/07 06:24:32  -Trying to convert datatype for POS: Int64 -> Int64...
2026/03/07 06:24:33  -Position bound:(0 , 250,000,000)
2026/03/07 06:24:33  -No outlier variants were removed.
2026/03/07 06:24:35  -Removed variants with bad positions: 0
2026/03/07 06:24:35 Finished fixing basepair positions (POS).
2026/03/07 06:24:35 Start to fix alleles (EA and NEA) ...(v4.0.4)
2026/03/07 06:24:35  -Converted all bases to string datatype and UPPERCASE
2026/03/07 06:24:37  -Variants with bad EA: 0
2026/03/07 06:24:37  -Variants with bad NEA: 0
2026/03/07 06:24:37  -Variants with NA for EA or NEA: 0
2026/03/07 06:24:37  -Variants with same EA and NEA: 1950599
2026/03/07 06:24:46 Finished fixing alleles (EA and NEA).
2026/03/07 06:24:46 Start to perform sanity check for statistics ...(v4.0.4)
2026/03/07 06:24:46  -Comparison tolerance for floats: 1e-07
2026/03/07 06:24:46  -Checking if any columns are empty...
2026/03/07 06:24:48  -Checking if -1e-07 < EAF < 1.0000001 : removed 0 variants.
2026/03/07 06:24:50  -Checking if -1e-07 < P < 1.0000001 : removed 0 variants.
2026/03/07 06:24:51  -Checking if -100.0000001 < BETA < 100.0000001 : removed 0 variants.
2026/03/07 06:24:52  -Checking if -1e-07 < SE < inf : removed 0 variants.
2026/03/07 06:24:52  -Checking STATUS and converting STATUS to Int64....
2026/03/07 06:24:52  -No variants were removed with bad statistics in total.
2026/03/07 06:24:52 Finished sanity check for statistics.
2026/03/07 06:24:52 Start to normalize indels ...(v4.0.4)
2026/03/07 06:24:52  -Number of threads/cores to use: 6
2026/03/07 06:24:52  -No available variants to normalize..
2026/03/07 06:24:52 Finished normalizing indels.
2026/03/07 06:24:52 Start to reorder the columns ...(v4.0.4)
2026/03/07 06:24:52  -Reordering columns to    : SNPID,CHR,POS,EA,NEA,STATUS,EAF,BETA,SE,P
2026/03/07 06:24:53 Finished reordering the columns.
2026/03/07 06:24:53 Start to sort the genome coordinates ...(v4.0.4)
2026/03/07 06:25:00 Finished sorting coordinates.
2026/03/07 06:25:00 Start to check if NEA is aligned with reference sequence ...(v4.0.4)
2026/03/07 06:25:00  -Reference genome FASTA file: /mnt/hdd_1/ofgeha/galaxy-gwas-tools/Data/hg38.fa
2026/03/07 06:25:08    -Loading and building numpy fasta records:
2026/03/07 06:25:14  -Variants allele on given reference sequence :  0
2026/03/07 06:25:14  -Variants flipped :  0
2026/03/07 06:25:14   -Raw Matching rate :  0.00%
2026/03/07 06:25:14 #WARNING! Matching rate is low, please check if the right reference genome is used.
2026/03/07 06:25:14  -Variants inferred reverse_complement :  0
2026/03/07 06:25:14  -Variants inferred reverse_complement_flipped :  0
2026/03/07 06:25:14  -Both allele on genome + unable to distinguish :  0
2026/03/07 06:25:14  -Variants not on given reference sequence :  0
2026/03/07 06:25:14 Finished checking if NEA is aligned with reference sequence.
2026/03/07 06:25:14 Start to adjust statistics based on STATUS code ...(v4.0.4)
2026/03/07 06:25:14  -No statistics have been changed.
2026/03/07 06:25:14 Finished adjusting statistics based on STATUS code.
2026/03/07 06:25:15 Start to infer strand for palindromic SNPs/align indistinguishable indels ...(v4.0.4)
2026/03/07 06:25:15  -Number of threads/cores to use: 6
2026/03/07 06:25:15 #WARNING! Reference file not found: /mnt/hdd_1/ofgeha/gwas-sumstats-harmoniser/gwas-ref/homo_sapiens-chr*.vcf.gz. Using default format.
2026/03/07 06:25:15  -Field for alternative allele frequency in VCF INFO: AF
2026/03/07 06:25:15  -Identified  1660921  palindromic SNPs...
2026/03/07 06:25:15  -After filtering by MAF<= 0.4 , 0 palindromic SNPs with unknown strand will be inferred...
2026/03/07 06:25:15 #WARNING! No palindromic variants available for checking.
2026/03/07 06:25:16   -Non-palindromic :  9169689
2026/03/07 06:25:17   -Palindromic SNPs on + strand:  0
2026/03/07 06:25:17   -Palindromic SNPs on - strand and needed to be flipped: 0
2026/03/07 06:25:18   -Palindromic SNPs with MAF not available to infer :  86113
2026/03/07 06:25:19   -Palindromic SNPs lacking reference matches, or with reference ALT unavailable or above MAF threshold for inference :  0
2026/03/07 06:25:19  -Identified  0  indistinguishable Indels...
2026/03/07 06:25:19 #WARNING! No indistinguishable indels available for checking.
2026/03/07 06:25:19 Finished inferring strand for palindromic SNPs/align indistinguishable indels.
2026/03/07 06:25:19 Start to adjust statistics based on STATUS code ...(v4.0.4)
2026/03/07 06:25:19  -No statistics have been changed.
2026/03/07 06:25:19 Finished adjusting statistics based on STATUS code.
2026/03/07 06:25:20 Start to remove duplicated/multiallelic variants ...(v4.0.4)
2026/03/07 06:25:20  -Removing mode:dm
2026/03/07 06:25:20 Start to sort the sumstats using P ...
2026/03/07 06:25:23 Start to remove duplicated variants based on snpid ...(v4.0.4)
2026/03/07 06:25:23  -Which variant to keep:  first
2026/03/07 06:25:34  -Removed variants based on SNPID: 0
2026/03/07 06:25:34 Start to remove duplicated variants based on CHR,POS,EA and NEA ...
2026/03/07 06:25:34  -Which variant to keep:  first
2026/03/07 06:25:42  -Removed variants based on CHR,POS,EA and NEA: 978
2026/03/07 06:25:42 Start to remove multiallelic variants based on chr:pos ...
2026/03/07 06:25:42  -Current Dataframe shape : 13778907 x 10 ; Memory usage: 1043.31 MB
2026/03/07 06:25:42  -Which variant to keep:  first
2026/03/07 06:25:52  -Removed variants multiallelic variants: 17251
2026/03/07 06:25:52  -Removed variants in total: 18229
2026/03/07 06:25:52  -Sort the coordinates based on CHR and POS...
2026/03/07 06:26:03 Finished removing duplicated/multiallelic variants.
2026/03/07 06:26:03 Start to sort the genome coordinates ...(v4.0.4)
2026/03/07 06:26:10 Finished sorting coordinates.
2026/03/07 06:26:10 Start to reorder the columns ...(v4.0.4)
2026/03/07 06:26:10  -Reordering columns to    : SNPID,CHR,POS,EA,NEA,STATUS,EAF,BETA,SE,P
2026/03/07 06:26:10 Finished reordering the columns.

In [ ]:
mysumstats.liftover(from_build="19", to_build="38")

2026/03/07 06:22:17 Start to perform liftover ...(v4.0.4)
2026/03/07 06:22:17 No records in config file. Please download first.
2026/03/07 06:22:17 37to38  is not available. Please use check_available_ref() to check available reference files.
2026/03/07 06:22:17 No records in config file. Please download first.

UnboundLocalError: cannot access local variable '_process_build' where it is not associated with a value

In [16]:
mysumstats = gl.Sumstats(
    "/mnt/hdd_1/ofgeha/gwas-sumstats-harmoniser/Data/21001_raw.gwas.imputed_v3.both_sexes.tsv",
    fmt="auto")

2026/03/07 08:06:33 GWASLab v4.0.4 https://cloufield.github.io/gwaslab/
2026/03/07 08:06:33 (C) 2022-2026, Yunye He, Kamatani Lab, GPL-3.0 license, gwaslab@gmail.com
2026/03/07 08:06:33 Python version: 3.12.3 (main, Jan 22 2026, 20:57:42) [GCC 13.3.0]
2026/03/07 08:06:33 Start to load format from formatbook....
2026/03/07 08:06:33  -auto format meta info:
2026/03/07 08:06:33   - format_name  : auto
2026/03/07 08:06:33   - format_separator  : \t
2026/03/07 08:06:33   - format_na  : #NA
2026/03/07 08:06:33   - format_assumption  : Note: auto-detection assumes A1=EA; Alt=EA and Frq=EAF
2026/03/07 08:06:33   - format_version  :  20230328
2026/03/07 08:06:33   - Auto-detection mode. Note: auto-detection assumes A1=EA; Alt=EA and Frq=EAF...
2026/03/07 08:06:33   - Header conversion source: https://github.com/Cloufield/formatbook/blob/main/formats/auto.json
2026/03/07 08:06:33 Start to initialize gl.Sumstats from file :/mnt/hdd_1/ofgeha/gwas-sumstats-harmoniser/Data/21001_raw.gwas.imputed_v3.both_sexes.tsv

2026/03/07 08:06:40  -Reading columns          : se,beta
2026/03/07 08:06:40  -Renaming columns to      : SE,BETA
2026/03/07 08:06:40  -Current Dataframe shape : 13791467  x  2
2026/03/07 08:06:41  -Initiating a status column: STATUS ...
2026/03/07 08:06:41 #WARNING! Version of genomic coordinates is unknown for homo sapiens (build: 99)...
2026/03/07 08:06:41 Start to reorder the columns ...(v4.0.4)
2026/03/07 08:06:41  -Reordering columns to    : STATUS,BETA,SE
2026/03/07 08:06:43 Finished reordering the columns.
2026/03/07 08:06:44 #WARNING!  -No rsID/SNPID and missing CHR/POS; created empty SNPID
2026/03/07 08:06:44  -Column  : STATUS BETA    SE      SNPID
2026/03/07 08:06:44  -DType   : int64  float64 float64 string
2026/03/07 08:06:44  -Verified: T      T       T       T
2026/03/07 08:06:45  -Current Dataframe memory usage: 420.88 MB
2026/03/07 08:06:45 Finished loading data successfully!

In [19]:
mysumstats.data

           STATUS        BETA           SE SNPID
0         9999999  894.616000  1204.870000  <NA>
1         9999999   -2.715450     2.360060  <NA>
2         9999999   -0.484284     0.423462  <NA>
3         9999999   -2.703560     2.360130  <NA>
4         9999999   -0.016436     0.019585  <NA>
...           ...         ...          ...   ...
13791462  9999999   -0.016260     0.010723  <NA>
13791463  9999999   -0.027098     0.011190  <NA>
13791464  9999999   -0.020494     0.011278  <NA>
13791465  9999999   -0.016347     0.010721  <NA>
13791466  9999999    0.007107     0.036783  <NA>

[13791467 rows x 4 columns]

In [21]:
mysumstats.columns

Index(['STATUS', 'BETA', 'SE', 'SNPID'], dtype='object')

In [22]:
mysumstats = gl.Sumstats(
    "/mnt/hdd_1/ofgeha/gwas-sumstats-harmoniser/Data/21001_raw.gwas.imputed_v3.both_sexes.tsv",
    snpid="variant",
    ea="minor_allele",
    eaf="minor_AF",
    beta="beta",
    se="se",
    p="pval",
    n="n_complete_samples",
    other=["low_confidence_variant", "AC", "ytx"]
)

2026/03/07 08:11:26 GWASLab v4.0.4 https://cloufield.github.io/gwaslab/
2026/03/07 08:11:26 (C) 2022-2026, Yunye He, Kamatani Lab, GPL-3.0 license, gwaslab@gmail.com
2026/03/07 08:11:26 Python version: 3.12.3 (main, Jan 22 2026, 20:57:42) [GCC 13.3.0]
2026/03/07 08:11:26 Start to initialize gl.Sumstats from file :/mnt/hdd_1/ofgeha/gwas-sumstats-harmoniser/Data/21001_raw.gwas.imputed_v3.both_sexes.tsv
2026/03/07 08:11:40  -Reading columns          : ytx,low_confidence_variant,n_complete_samples,minor_allele,variant,pval,se,AC,minor_AF,beta
2026/03/07 08:11:40  -Renaming columns to      : ytx,low_confidence_variant,N,EA,SNPID,P,SE,AC,EAF,BETA
2026/03/07 08:11:40  -Current Dataframe shape : 13791467  x  10
2026/03/07 08:11:40  -Initiating a status column: STATUS ...
2026/03/07 08:11:40 #WARNING! Version of genomic coordinates is unknown for homo sapiens (build: 99)...
2026/03/07 08:11:41 Start to reorder the columns ...(v4.0.4)
2026/03/07 08:11:41  -Reordering columns to    : SNPID,EA,STATUS,EAF,BETA,SE,P,N,low_confidence_variant,AC,ytx
2026/03/07 08:11:41 Finished reordering the columns.
2026/03/07 08:11:41  -Column  : SNPID  EA       STATUS EAF     BETA    SE      P       N     low_confidence_variant AC      ytx
2026/03/07 08:11:41  -DType   : object category int64  float64 float64 float64 float64 int64 bool                   float64 float64
2026/03/07 08:11:41  -Verified: T      T        T      T       T       T       T       T     NA                     NA      NA
2026/03/07 08:11:41  -Current Dataframe memory usage: 1014.01 MB
2026/03/07 08:11:42 Finished loading data successfully!

In [26]:
mysumstats.data

,SNPID,EA,STATUS,EAF,BETA,SE,P,N,low_confidence_variant,AC,ytx
0,1:15791:C:T,T,9999999,5.446880e-09,894.616000,1204.870000,0.457786,359983,True,0.003922,1.238950e-01
1,1:69487:G:A,A,9999999,5.768250e-06,-2.715450,2.360060,0.249902,359983,True,4.152940,1.035150e+02
2,1:69569:T:C,C,9999999,1.878960e-04,-0.484284,0.423462,0.252778,359983,True,135.278000,3.644560e+03
3,1:139853:C:T,T,9999999,5.681100e-06,-2.703560,2.360130,0.251997,359983,True,4.090200,1.018400e+02
4,1:692794:CA:C,C,9999999,1.105900e-01,-0.016436,0.019585,0.401342,359983,False,79621.100000,2.179000e+06
...,...,...,...,...,...,...,...,...,...,...,...
13791462,X:154929412:C:T,T,9999999,2.454730e-01,-0.016260,0.010723,0.129427,359983,False,176732.000000,4.837480e+06
13791463,X:154929637:CT:C,C,9999999,2.297260e-01,-0.027098,0.011190,0.015456,359983,False,165395.000000,4.525550e+06
13791464,X:154929952:CAA:C,C,9999999,2.394300e-01,-0.020494,0.011278,0.069202,359983,False,172381.000000,4.717910e+06
13791465,X:154930230:A:G,G,9999999,2.458870e-01,-0.016347,0.010721,0.127334,359983,False,177030.000000,4.845680e+06
13791466,X:154930487:T:A,A,9999999,1.955900e-02,0.007107,0.036783,0.846790,359983,False,14081.800000,3.857390e+05